# Generated by Django 4.1.5 on 2023-01-21 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_updated',
        ),
    ]
